# Generated by Django 5.2.4 on 2025-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
